### ISSUE TITLE
Still will not install on Mac

### ISSUE THREAD

**Issue by Sod-Almighty** [PinguinoIDE/pinguino-installers#13]
> ./installer.sh: line 32: [/Applications/Xcode.app/Contents/Developer=/Applications/Xcode.app/Contents/Developer]: No such file or directory
ERROR: No Xcode Instalation found.
Please install Xcode and continue with this script

I have xcode. It is installed. It is working. Your script, however, seems incapable of finding it.

Seems this issue was first reported to you in November 2011, and apparently nothing has been done about it in the subsequent year and a half. Do you plan to fix this at any point? Or should we all consider the Mac version of Penguino to be utterly dead?

FWIW, I am running MacOS 10.11.6 El Crapitan.

**Comment by MefhigosetH** [comment]
Dear @Sod-Almighty ,

Sory for the delay.

We currently haven't support on MAC, because the lack of test environment. So we not recommend any MacOs Pingüino installer now, almost se can fix this.

If you could install manually and it's work, please, let me known about this.

I plan publish a manual installation guide for GNU/Linux, on the Pingüino Website soon.

Thanks for your contact

**Comment by Sod-Almighty** [comment]
Why have you closed this?

**Comment by MefhigosetH** [comment]
Mmm... Because it doesn't have any uptdate in months. Do you keep it open?

**Comment by Sod-Almighty** [comment]
To my mind, issues should remain open until they are fixed. Don't you think?
