### ISSUE TITLE
Can't be run pinguino

### ISSUE THREAD

**Issue by szybkijanek** [PinguinoIDE/pinguino-installers#21]
Hi, after install pinguino on fresh Ubuntu 20.04 from Yt tutorial i have this error:
_qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem._

_Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb._

_Aborted (core dumped)_

I try installing many times with new installation Ubuntu but still same problem. My Ubuntu is on VMware

**Comment by MefhigosetH** [comment]
Dear @szybkijanek , thanks for your contact.

Please, execute `export QT_DEBUG_PLUGINS=1` in your terminal before open the Pinguino IDE, so we can see de full debug error and the real cause of the problem. Paste the new error back here.

You see something similar to this:

![image](https://user-images.githubusercontent.com/527738/116879551-24f15680-abf7-11eb-93b3-94c6a71d5f0b.png)


Thanks in advance.

**Comment by MefhigosetH** [comment]
Or you can try install a common missing library:

`sudo apt install libxcb-xinerama0`

**Comment by szybkijanek** [comment]
Installing this library solve problem. Thank You.

**Comment by fpeixeiro** [comment]
Hello,
Sorry to wake up an old thread, but it happened the same to me and the library didn't solve the problem.

Here's the debug error output:
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
Cannot load library /home/fernando/.local/share/virtualenvs/pinguino-ide-fix-linux-support-KSH-IpCP/lib/python3.7/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-util.so.1: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/home/fernando/.local/share/virtualenvs/pinguino-ide-fix-linux-support-KSH-IpCP/lib/python3.7/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /home/fernando/.local/share/virtualenvs/pinguino-ide-fix-linux-support-KSH-IpCP/lib/python3.7/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-util.so.1: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted

Best regards,
Fernando Peixeiro
